### ISSUE TITLE
Theme for Select and Validation

### ISSUE THREAD

**Issue by pippo111** [smooth-code/smooth-ui#110]
## 💬 Questions and Help

In default theme I can add styling for inputs. I would be great if the styles applied to inputs also be applied to select items. Is there any option for setting background color for select in theme.js or I need to set it by the class names in global stylesheet ?

**Comment by neoziro** [comment]
Hello @pippo111, I think we can't style them I am sorry..

**Comment by midnightcodr** [comment]
You can't style them directly but you can use the following (tested) workaround
```js
import { createGlobalStyle } from 'styled-components'
import { th } from '@smooth-ui/core-sc'

const GlobalStyle = createGlobalStyle`
  .select select {
    color: white;
    background-color: ${th('blue')};
  }
`
```
And make sure you apply `GlobalStyle` in your root component like [this](https://www.styled-components.com/docs/api#createglobalstyle)

Later on in your component,
```jsx
<Select
  className='select'
  ...
/>
```

If you try to style `Select` using styled-components, it won't work either because, take the following code for example,
```jsx
const CustomSelect = styled(Select)`
  background-color: ${th('blue')};
`

export default () => (
  <CustomSelect ... />
)
```
The `background-color` attribute only applies to the wrapper around the rendered `select` html element, which does not inherit the wrapper's background-color
