### ISSUE TITLE
Differences with Rebass and Reakit

### ISSUE THREAD

**Issue by Grsmto** [smooth-code/smooth-ui#74]
Hi guys,

I'm currently actively looking into different React UI frameworks and I love the common pattern between _Smooth UI_, _Reakit_ and _Rebass_ of using primitive components and "systems".
My problem is that I'm having issues to choose which one to use!

From what I see you solved some issues from Styled-System or chose different path (for example using an object for media queries instead of an array). I think that would be great to have this history written down somewhere.
I read the code and I think documenting it could also be really helpful for users to do their choice (for example [this file](https://github.com/smooth-code/smooth-ui/blob/master/packages/shared/core/styled-engine/index.js) is confusing to me but I'm sure there is a good reason for it). 

That would be really helpful to have the short story behind the different design decisions done in this UI library!

Thanks!

**Comment by neoziro** [comment]
Hello @Grsmto,

You are right, I don't want to do a comparison between other UI libraries because I think I am not in the position to do it. But I can explain my choices and the history quickly to help you choose:

### Styled System

At start, Smooth UI didn't have a style system. While I worked on a project, I decided to use [styled-system](https://github.com/jxnblk/styled-system/). I immediately saw the power and the value of it, development was way faster.

After that, I decided to add one in Smooth UI. My first choice was "styled-system", but after a deep look I found the performance issues. And some design choice was not fitting my needs. I wanted something simple and fully integrated in Smooth UI. That's why I build a custom one for my own needs, in the philosophy of Smooth UI and performance oriented. This is the reason why I use an object instead of an array, it is simpler for the user to understand what's going on and it is more flexible (adding a breakpoint will not break your website).

### Styled Components & Emotion

At start, Smooth UI was only compatible with Styled Components. But I worked on a project that was using Emotion, that's why I decided to compatibility for it. Also I was able to reach all users using Emotion. 

The other reason I decided to add support for Emotion was the performance. Styled Components v3 suffered of perf issues and Emotion was much more performant. Today it is no longer true, so the interest of supporting both is reduced. But it doesn't cost a lot, so I will stay like it for a while.

[The file](https://github.com/smooth-code/smooth-ui/blob/master/packages/shared/core/styled-engine/index.js) you are pointing out is just here for linting issue, this file is replaced by [emotion file](https://github.com/smooth-code/smooth-ui/blob/master/packages/shared/core/styled-engine/emotion.js) or [styled-components file](https://github.com/smooth-code/smooth-ui/blob/master/packages/shared/core/styled-engine/styled-components.js) during the build.

I hope I answered your questions and that I made your choice easier!

**Comment by rafaelchiti** [comment]
Thanks for sharing context! I wonder what performance issues you encountered with styled-system? I'm using both (styled-system in one project, that required a tailored made design system and sponsoring another project using smooth ui).

Thanks!

**Comment by neoziro** [comment]
I don't remember but it was mostly iteration on object properties. Smooth UI iterates over component properties, styled-system iterates over all accepted properties.
