### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by mvasin** [smooth-code/smooth-ui#79]
Do TypeScript definitions exist for Smooth UI?

**Comment by neoziro** [comment]
Not yet I think.

**Comment by brandontle** [comment]
Would also love to see Typescript definitions for Smooth.

**Comment by Ermakoy** [comment]
I can try to implement it.

**Comment by Ermakoy** [comment]
You want to implement just external types like props for components or make definitions for all package internal functions, utils and components props?

**Comment by neoziro** [comment]
I would like types for all functions & components exposed to the user.

**Comment by Ermakoy** [comment]
Sorry for big delay, have some troubles. 
Currently working on types for components

**Comment by Ermakoy** [comment]
@neoziro 
Please, have a look to PR solving this

**Comment by ReasonableDeveloper** [comment]
Hey @Ermakoy. In this [issue](https://github.com/smooth-code/smooth-ui/issues/109) I found out that types will no longer be part of this repository. Could you put the types onto the [definitely typed repostory](https://github.com/DefinitelyTyped/DefinitelyTyped). Even if not all the latest types are valid, I would love to contribute as I've started monkey patching some `smooth-ui` types in my project but ultimately had to set `skipLibCheck: true` due to being new to `TypeScript`.

**Comment by Ermakoy** [comment]
Hello, @ReasonableDeveloper.
Ok, i will upload types

**Comment by willredington** [comment]
was this ever uploaded?

**Comment by iilei** [comment]
any chance for a `@types/smooth-ui__core-sc` package?

**Comment by RoryOfByrne** [comment]
+1 I'd like to use Smooth UI but there's no types available so I'm not using it.
